
# 数据库玩家匹配模式
# 【一旦确定该选项，就不要再更改】
# true  - 使用UUID匹配玩家，适合正版、外置登录服务器
# false - 使用玩家名匹配玩家，适合离线模式服务器
# auto  - 根据 server.properties 里的选项确定 true 或 false
online-mode: auto

# 在控制台成功增加数值时不提示
console-silent-plus: true

# 是否开启不安全模式
# 在不安全模式下，即使服务器内没有玩家，也可以设置全局数值
# 如果这么做，且你在多个服务器安装了本插件，多个服务器之间的缓存有可能会出现不同步的情况！
unsafe-mode: false
